#dbUserPasswords:
#  dbuserPassword: ""

databases:
  mosip_toolkit:
    enabled: true
    scriptsDir: mosip_toolkit      # fixed - must match db_scripts/ folder in repo
    dbName: mosip_toolkit          # customize e.g. mosip_toolkit02
    dbUser: toolkituser           # customize e.g. toolkituser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/mosip-compliance-toolkit.git
    branch: develop
